name: WebEngineering Auto Time Update

on:
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch:

jobs:
  update-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update date and time
        run: |
          CURRENT_DATE=$(date +"%A, %d %B %Y")
          CURRENT_TIME=$(date +"%H:%M:%S")
          TOTAL_COMMITS=$(git rev-list --all --count)

          echo "WebEngineering Automatic Update Log" > dailyTimeDateUpdation
          echo "------------------------------------" >> dailyTimeDateUpdation
          echo "Date: $CURRENT_DATE" >> dailyTimeDateUpdation
          echo "Time: $CURRENT_TIME" >> dailyTimeDateUpdation
          echo "Total Commits: $TOTAL_COMMITS" >> dailyTimeDateUpdation

      - name: Commit and Push Changes
        run: |
          git config --global user.name "auto-update-bot"
          git config --global user.email "bot@github.com"
          git add dailyTimeDateUpdation
          git commit -m "Automatic date & time update"
          git push
